CREATE DATABASE users;

USE users;

CREATE TABLE user (
    id CHAR(36) PRIMARY KEY NOT NULL DEFAULT (UUID()),
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);